/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/model/airplane.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/airplane.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle001.geometry} material={materials.plane} position={[0, -0.004, -9.127]} rotation={[0, 0.604, 0]} scale={17.454} />
      <mesh geometry={nodes.PUSHILIN_Plane_Circle002.geometry} material={materials.plane} position={[0, -0.004, -9.127]} rotation={[0, 0.604, 0]} scale={17.454} />
    </group>
  )
}

useGLTF.preload('/airplane.gltf')
