/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/model/clouds.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/clouds.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mball001.geometry} material={nodes.Mball001.material} />
    </group>
  )
}

useGLTF.preload('/clouds.gltf')
