/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/model/airplane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const HELIX_SPEED = 6;
export function Airplane(props) {
  const { nodes, materials } = useGLTF('/models/model/airplane.glb')
  
  const helix = useRef()

  useFrame((_state,delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED
  })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} />
      <mesh ref={helix} geometry={nodes.PUSHILIN_Plane_Circle001.geometry} material={materials.plane} />
    </group>
  )
}

useGLTF.preload('/models/model/airplane.glb')
