/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/model/cloud.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud({opacity,...props}) {
  const { nodes, materials } = useGLTF('/models/model/cloud.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial {...materials.lambert2SG} transparent opacity={opacity}/>
        </mesh>
    </group>
  )
}

useGLTF.preload('/models/model/cloud.glb')
